- project:
    check:
      jobs:
        - monasca-tempest-python-mysql:
            voting: false
        - monasca-tempest-python-postgresql:
            voting: false
        - monasca-tempest-java-mysql:
            voting: false
        - monasca-tempest-java-postgresql:
            voting: false
        - legacy-monasca-thresh-maven-build
    gate:
      jobs:
        - legacy-monasca-thresh-maven-build
    post:
      jobs:
        - legacy-monasca-thresh-localrepo-upload
