- project:
    check:
      jobs:
        - monasca-tempest-python3-influxdb:
            voting: false
        - monasca-tempest-python3-cassandra:
            voting: false
        - monasca-tempest-java-influxdb:
            voting: false
        - monasca-tempest-java-cassandra:
            voting: false
        - legacy-monasca-thresh-maven-build
    gate:
      jobs:
        - legacy-monasca-thresh-maven-build
    post:
      jobs:
        - legacy-monasca-thresh-localrepo-upload
